import { useEffect, useRef, useState } from 'react'
import { mensajeErrorAdmin, restablecerContrasena } from '../api/adminApi'

export default function ModalRestablecerPassword({ usuario, onClose }) {
  const closeRef = useRef(null); const [metodo, setMetodo] = useState('correo'); const [temporal, setTemporal] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState('')
  useEffect(() => { closeRef.current?.focus(); const key = e => e.key === 'Escape' && onClose(); document.addEventListener('keydown', key); return () => { setTemporal(''); document.removeEventListener('keydown', key) } }, [onClose])
  const enviar = async () => { setBusy(true); setError(''); try { const result = await restablecerContrasena(usuario.id, metodo); if (metodo === 'correo') { onClose() } else { setTemporal(result.passwordTemporal || '') } } catch (e) { setError(mensajeErrorAdmin(e)) } finally { setBusy(false) } }
  return <div className="sa-modal-backdrop"><section className="sa-modal" role="dialog" aria-modal="true" aria-labelledby="sa-pass-title"><button ref={closeRef} className="sa-modal__close" onClick={onClose} aria-label="Cerrar">×</button><h2 id="sa-pass-title">Restablecer contraseña</h2><p>La contraseña actual nunca puede consultarse. Al restablecerla se cerrarán todas las sesiones del usuario.</p>{error && <div className="sa-error">{error}</div>}{temporal ? <div className="sa-temporal"><small>Contraseña temporal · se muestra una sola vez</small><strong>{temporal}</strong><button onClick={() => navigator.clipboard.writeText(temporal)}>Copiar</button></div> : <><label><input type="radio" checked={metodo === 'correo'} onChange={() => setMetodo('correo')}/> Enviar enlace por correo</label><label><input type="radio" checked={metodo === 'temporal'} onChange={() => setMetodo('temporal')}/> Generar contraseña temporal</label><button className="sa-primary" disabled={busy} onClick={enviar}>{busy ? 'Procesando…' : 'Restablecer'}</button></>}</section></div>
}
